language: python

dist: bionic

cache: pip

services:
    - docker

env:
    matrix:
        - ELASTIC_VERSION=2.4.6
        - ELASTIC_VERSION=1.7.6

before_install:
    - docker pull "elasticsearch:${ELASTIC_VERSION}"
    - docker run -d -p 9200:9200 -e "discovery.type=single-node" --tmpfs "/usr/share/elasticsearch/data" "elasticsearch:${ELASTIC_VERSION}"
    - scripts/wait-for-elastic.sh

script:
    - nosetests
    - flake8
